name=Adafruit ADS7128
version=1.0.0
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
sentence=Arduino library for TI ADS7128 8-Channel 12-Bit ADC with GPIOs and CRC
paragraph=Arduino library for TI ADS7128 Small, 8-Channel, 12-Bit ADC With I2C Interface, GPIOs, and CRC
category=Sensors
url=https://github.com/adafruit/Adafruit_ADS7128
architectures=*
depends=Adafruit BusIO
